-- Chap Khana Ordering System — Supabase PostgreSQL
-- Run ONCE in the Supabase SQL Editor. This is a fresh install schema.
-- Security model: anonymous users see only active menu/settings; orders are
-- created by a DB-validated RPC, never by a client INSERT. Staff permissions
-- are enforced by RLS and an explicit allowlist of auth.users IDs.

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to anon, authenticated;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id text primary key,
  category text not null check (category in ('chap','grill','special','sides')),
  name text not null check (length(name) between 1 and 120),
  name_bn text not null default '',
  description text not null default '',
  description_bn text not null default '',
  price integer check (price between 1 and 999999),
  image_url text not null default '',
  badge text not null default '',
  sort_order integer not null default 100,
  active boolean not null default true,
  available boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.store_settings (
  id integer primary key default 1 check(id=1),
  accepting_orders boolean not null default false,
  pickup_enabled boolean not null default true,
  delivery_enabled boolean not null default false,
  delivery_fee integer not null default 0 check (delivery_fee between 0 and 5000),
  updated_at timestamptz not null default now(),
  check (pickup_enabled or delivery_enabled)
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  tracking_token uuid not null default gen_random_uuid() unique,
  customer_user_id uuid references auth.users(id) on delete set null,
  customer_name text not null,
  customer_phone text not null,
  fulfillment_type text not null check (fulfillment_type in ('pickup','delivery')),
  delivery_address text not null default '',
  notes text not null default '',
  status text not null default 'pending' check (status in ('pending','confirmed','preparing','ready','out_for_delivery','completed','cancelled')),
  subtotal integer not null check (subtotal>0),
  delivery_fee integer not null check (delivery_fee>=0),
  total integer not null check (total=subtotal+delivery_fee),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id text references public.menu_items(id) on delete set null,
  item_name text not null,
  unit_price integer not null check (unit_price>0),
  qty integer not null check (qty between 1 and 20),
  line_total integer not null check (line_total = qty*unit_price)
);

create index if not exists orders_customer_user_idx on public.orders (customer_user_id, created_at desc);
create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status, created_at desc);
create index if not exists order_items_order_idx on public.order_items (order_id);

-- Turn RLS on for EVERY public table.
alter table public.admin_users enable row level security;
alter table public.menu_items enable row level security;
alter table public.store_settings enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Allowlist helper is PRIVATE and uses a pinned search_path.
create or replace function private.is_staff()
returns boolean
language sql stable security definer set search_path = ''
as $$
  select exists (select 1 from public.admin_users where user_id = (select auth.uid()));
$$;
revoke all on function private.is_staff() from public, anon, authenticated;
grant execute on function private.is_staff() to authenticated;

-- Table permissions: no browser user can directly create an order or edit prices
-- unless a policy explicitly allows a staff operation.
revoke all on public.admin_users, public.menu_items, public.store_settings, public.orders, public.order_items from anon, authenticated;
grant select on public.menu_items, public.store_settings to anon, authenticated;
grant select on public.admin_users to authenticated;
grant insert, update on public.menu_items to authenticated;
grant update on public.store_settings to authenticated;
grant select, update on public.orders to authenticated;
grant select on public.order_items to authenticated;

create policy "staff see their own membership"
on public.admin_users for select to authenticated
using (user_id = (select auth.uid()));

create policy "public see active dishes"
on public.menu_items for select to anon, authenticated using (active);
create policy "staff see inactive dishes"
on public.menu_items for select to authenticated using ((select private.is_staff()));
create policy "staff add dishes"
on public.menu_items for insert to authenticated
with check ((select private.is_staff()));
create policy "staff edit dishes"
on public.menu_items for update to authenticated
using ((select private.is_staff())) with check ((select private.is_staff()));

create policy "anyone can see settings"
on public.store_settings for select to anon, authenticated using (true);
create policy "staff can change settings"
on public.store_settings for update to authenticated
using ((select private.is_staff())) with check ((select private.is_staff()));

create policy "staff see all orders"
on public.orders for select to authenticated using ((select private.is_staff()));
create policy "customers read own orders"
on public.orders for select to authenticated
using (customer_user_id = (select auth.uid()));
create policy "customers read own items"
on public.order_items for select to authenticated
using (exists (select 1 from public.orders o where o.id = order_id and o.customer_user_id = (select auth.uid())));
create policy "staff update order statuses"
on public.orders for update to authenticated
using ((select private.is_staff())) with check ((select private.is_staff()));
create policy "staff see order lines"
on public.order_items for select to authenticated using ((select private.is_staff()));

-- All prices and totals below are computed from trusted menu_items rows.
-- The user NEVER passes a price, discount or delivery fee.
create or replace function private.place_order_impl(
  p_name text, p_phone text, p_type text, p_address text, p_notes text, p_items jsonb
)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
declare
  v_cfg public.store_settings%rowtype;
  v_line record;
  v_menu public.menu_items%rowtype;
  v_subtotal integer := 0;
  v_fee integer := 0;
  v_order_id uuid := gen_random_uuid();
  v_token uuid := gen_random_uuid();
  v_code text := 'CK-' || upper(substring(replace(v_order_id::text,'-','') from 1 for 10));
  v_count integer;
begin
  select * into v_cfg from public.store_settings where id = 1;
  if not found or not v_cfg.accepting_orders then
    raise exception 'Online ordering is currently closed.';
  end if;
  if p_type not in ('pickup','delivery') or
     (p_type='pickup' and not v_cfg.pickup_enabled) or
     (p_type='delivery' and not v_cfg.delivery_enabled) then
    raise exception 'This fulfillment method is unavailable.';
  end if;
  if length(trim(coalesce(p_name,''))) not between 2 and 80 then
    raise exception 'Please enter a valid name.';
  end if;
  if coalesce(p_phone,'') !~ '^(\+?88)?01[3-9][0-9]{8}$' then
    raise exception 'Please enter a valid Bangladesh mobile number.';
  end if;
  if p_type='delivery' and length(trim(coalesce(p_address,''))) not between 8 and 350 then
    raise exception 'A delivery address of at least 8 characters is required.';
  end if;
  if length(coalesce(p_notes,'')) > 500 then
    raise exception 'Order notes are too long.';
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) not between 1 and 25 then
    raise exception 'An order must have between 1 and 25 line items.';
  end if;
  -- Validate every line BEFORE inserting any order record.
  for v_line in select * from jsonb_array_elements(p_items) as entry(value) loop
    if jsonb_typeof(v_line.value) <> 'object' or
       jsonb_typeof(v_line.value->'id') <> 'string' or
       coalesce(v_line.value->>'qty','') !~ '^([1-9]|1[0-9]|20)$' then
      raise exception 'An order item is invalid.';
    end if;
  end loop;
  select count(distinct entry.value->>'id') into v_count
  from jsonb_array_elements(p_items) as entry(value);
  if v_count <> jsonb_array_length(p_items) then
    raise exception 'Duplicate items are not allowed.';
  end if;
  for v_line in select (value->>'id') as item_id, (value->>'qty')::integer as qty
                from jsonb_array_elements(p_items) loop
    select * into v_menu from public.menu_items
    where id=v_line.item_id and active and available and price is not null and price>0
    for share;
    if not found then
      raise exception 'An item is unavailable. Please refresh the menu.';
    end if;
    v_subtotal := v_subtotal + v_menu.price * v_line.qty;
  end loop;
  v_fee := case when p_type='delivery' then v_cfg.delivery_fee else 0 end;
  insert into public.orders(
    id, code, tracking_token, customer_user_id, customer_name, customer_phone, fulfillment_type,
    delivery_address, notes, subtotal, delivery_fee, total
  ) values (
    v_order_id, v_code, v_token, auth.uid(), trim(p_name), p_phone, p_type,
    case when p_type='delivery' then trim(p_address) else '' end,
    coalesce(trim(p_notes),''), v_subtotal, v_fee, v_subtotal+v_fee
  );
  for v_line in select (value->>'id') as item_id, (value->>'qty')::integer as qty
                from jsonb_array_elements(p_items) loop
    select * into v_menu from public.menu_items where id=v_line.item_id;
    insert into public.order_items(order_id,menu_item_id,item_name,unit_price,qty,line_total)
    values(v_order_id,v_menu.id,v_menu.name,v_menu.price,v_line.qty,v_menu.price*v_line.qty);
  end loop;
  return jsonb_build_object('code',v_code,'tracking_token',v_token,'total',v_subtotal+v_fee);
end;
$$;

-- Track with an unguessable bearer token only. No customer PII is returned.
create or replace function private.track_order_impl(p_token uuid)
returns jsonb
language sql stable security definer set search_path = ''
as $$
  select jsonb_build_object(
    'code',o.code,'status',o.status,'total',o.total,
    'fulfillment_type',o.fulfillment_type,'created_at',o.created_at
  ) from public.orders o where o.tracking_token=p_token limit 1;
$$;

-- EXPOSED API wrappers are SECURITY INVOKER, not SECURITY DEFINER.
-- PRIVATE implementations are not in any API-exposed schema.
create or replace function public.place_order(
  p_name text, p_phone text, p_type text, p_address text, p_notes text, p_items jsonb
) returns jsonb language sql volatile security invoker set search_path = ''
as $$select private.place_order_impl(p_name,p_phone,p_type,p_address,p_notes,p_items)$$;

create or replace function public.track_order(p_token uuid)
returns jsonb language sql stable security invoker set search_path = ''
as $$select private.track_order_impl(p_token)$$;

revoke all on function private.place_order_impl(text,text,text,text,text,jsonb) from public,anon,authenticated;
revoke all on function private.track_order_impl(uuid) from public,anon,authenticated;
revoke all on function public.place_order(text,text,text,text,text,jsonb) from public,anon,authenticated;
revoke all on function public.track_order(uuid) from public,anon,authenticated;
grant execute on function private.place_order_impl(text,text,text,text,text,jsonb) to anon,authenticated;
grant execute on function private.track_order_impl(uuid) to anon,authenticated;
grant execute on function public.place_order(text,text,text,text,text,jsonb) to anon,authenticated;
grant execute on function public.track_order(uuid) to anon,authenticated;

-- Public menu seeded with UNPRICED, unverified items; admin must confirm first.
-- Only owner-approved entries and prices should remain for public launch.
insert into public.menu_items
(id,category,name,name_bn,description,description_bn,price,image_url,badge,sort_order,active,available)
values
('chicken-chap','chap','Chicken Chap','চিকেন চাপ','Smoky, tender, boldly spiced.','ধোঁয়া ওঠা মশলাদার স্বাদ।',null,'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1000&q=80','Signature',1,true,true),
('beef-kala-bhuna','special','Beef Kala Bhuna','বিফ কালা ভুনা','Slow-cooked and full of warmth.','ধীরে রান্না করা গাঢ় স্বাদ।',null,'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=1000&q=80','',2,true,true),
('beef-nehari','special','Beef Nehari','বিফ নেহারি','Comfort food for sharing.','সবার সঙ্গে ভাগ করে খাওয়ার মতো।',null,'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1000&q=80','',3,true,true),
('tandoori-chicken','grill','Tandoori Chicken','তন্দুরি চিকেন','A little char, a lot of flavour.','হালকা পোড়া, মজাদার স্বাদ।',null,'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=1000&q=80','',4,true,true),
('grilled-chicken','grill','Grilled Chicken','গ্রিলড চিকেন','Fresh from the flame.','আগুনে গ্রিল করা স্বাদ।',null,'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1000&q=80','',5,true,true),
('naan','sides','Naan Bread','নান রুটি','A perfect pairing for your meal.','পছন্দের খাবারের সঙ্গে মানানসই।',null,'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=1000&q=80','',6,true,true)
on conflict (id) do nothing;

insert into public.store_settings(id,accepting_orders,pickup_enabled,delivery_enabled,delivery_fee)
values(1,false,true,false,0) on conflict(id) do nothing;

-- Verify after setup: SELECT * FROM public.menu_items; SELECT * FROM public.store_settings;
-- Create a user in Supabase > Authentication > Users. Assign staff ONLY via
-- the SQL Editor:
--   INSERT INTO public.admin_users(user_id)
--   SELECT id FROM auth.users WHERE email = 'OWNER-EMAIL@example.com'
--   ON CONFLICT (user_id) DO NOTHING;
-- Never grant staff membership from client code.
