import { ArrowLeft, ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useShop } from '../context/ShopContext';
import { money } from '../lib/utils';
import { discountedUnitPrice, unitSavings } from '../lib/discount';
import { DishImage } from '../components/DishCard';

export default function CartPage(){
  const {t,menu,cart,add,decrease,remove,subtotal,count,settings}=useShop();const items=menu.filter(i=>(cart[i.id]||0)>0);const savings=items.reduce((sum,item)=>sum+unitSavings(item)*(cart[item.id]||0),0);
  return <section className="site-wrap page-pad"><Link to="/menu" className="back-link"><ArrowLeft size={16}/> {t.browse}</Link><div className="page-heading-row"><div><div className="section-kicker"><span/> YOUR NEXT CRAVING</div><h1 className="page-title">{t.bag}<span className="text-ember">.</span></h1></div><span className="font-semibold text-[#927b69]">{count} items</span></div>
    {items.length===0?<div className="empty-state"><ShoppingBag size={48} className="mx-auto text-ember mb-5"/><h2 className="text-2xl font-bold">{t.empty}</h2><p className="text-[#8f8076] mt-2">{t.empty2}</p><Link className="btn-primary mt-6 inline-flex" to="/menu">{t.browse}<ArrowRight size={16}/></Link></div>:
    <div className="grid lg:grid-cols-[1.5fr_.75fr] gap-8 items-start"><div className="panel overflow-hidden">{items.map(item=><div className="cart-item" key={item.id}><div className="w-24 sm:w-28 h-24 shrink-0 rounded-md overflow-hidden"><DishImage item={item} large/></div><div className="grow"><h3 className="font-bold text-lg">{item.name}</h3><p className="text-sm text-[#81766e] mt-1">{unitSavings(item)>0?<><s className="mr-2">{money(item.price!)}</s><strong className="text-ember">{money(discountedUnitPrice(item)!)}</strong><span className="block text-green-700 text-xs mt-1">Save {money(unitSavings(item))} each</span></>:item.price?money(item.price):t.price}</p><div className="qty-controls mt-3"><button type="button" aria-label={`Decrease ${item.name}`} onClick={()=>decrease(item.id)}><Minus size={15}/></button><span>{cart[item.id]}</span><button type="button" aria-label={`Increase ${item.name}`} onClick={()=>add(item.id)} disabled={(cart[item.id]||0)>=20}><Plus size={15}/></button></div></div><div className="self-start text-right"><strong>{money((discountedUnitPrice(item)||0)*(cart[item.id]||0))}</strong><button className="block ml-auto text-[#a48a7b] mt-4 hover:text-red-600" aria-label={`Remove ${item.name}`} onClick={()=>remove(item.id)}><Trash2 size={17}/></button></div></div>)}</div>
      <div className="summary-card"><h2 className="text-xl font-bold mb-6">{t.review}</h2>{savings>0&&<div className="summary-line text-green-700"><span>Discount savings</span><strong>−{money(savings)}</strong></div>}<div className="summary-line"><span>{t.subtotal}</span><strong>{money(subtotal)}</strong></div><div className="summary-line"><span>{t.fee}</span><span>At checkout</span></div><div className="summary-line total-line"><span>{t.total}</span><strong>{money(subtotal)}</strong></div><Link to="/checkout" className={`btn-primary w-full justify-center mt-6 ${!settings.accepting_orders?'pointer-events-none opacity-50':''}`}>{t.checkout}<ArrowRight size={17}/></Link>{!settings.accepting_orders&&<p className="text-red-700 text-sm mt-4">Ordering is currently paused.</p>}<p className="text-xs text-[#9d8a7f] mt-5 leading-5">Your total is recalculated securely by the database when you place the order.</p></div></div>}
  </section>;
}
