-- Chap Khana brand/menu update v3.0, dated 2026-10.
-- SAFE for existing live databases: never deletes customer orders, and only changes
-- existing menu items if their price is NULL (the original unpriced seed records).
-- The names/prices are transcribed from user-supplied photographs and require
-- OWNER APPROVAL prior to enabling accepting_orders. Different historical
-- photographed menu cards contain contradictory prices. Coffee menu may be
-- offered by a different outlet; verify before launching online checkout.
-- Run AFTER 01_fresh_schema.sql and 03_production_hardening.sql, OR on an
-- existing database that already has public.menu_items and store_settings.

begin;

alter table public.menu_items drop constraint if exists menu_items_category_check;
alter table public.menu_items add constraint menu_items_category_check
  check (category in ('chap','beef','grill','naan','rice','salad','drinks','shakes','coffee','juice','dessert','special','sides'));

insert into public.menu_items
 (id,category,name,name_bn,description,description_bn,price,image_url,badge,sort_order,active,available)
values
  ('chicken-chap','chap','Chicken Chap','চিকেন চাপ','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',180,'','Popular',1,true,true),
  ('chicken-barbecue','chap','Chicken Barbecue','চিকেন বারবিকিউ','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',180,'','',2,true,true),
  ('tandoori-chicken','grill','Chicken Tandoori','চিকেন তন্দুরি','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',180,'','',3,true,true),
  ('chicken-boti-kebab','grill','Chicken Boti Kebab','চিকেন বটি কাবাব','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',180,'','',4,true,true),
  ('chicken-wings-bbq','grill','Chicken Wings BBQ','চিকেন উইংস বারবিকিউ','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',180,'','',5,true,true),
  ('chicken-malai-tandoori','grill','Chicken Malai Tandoori','চিকেন মালাই তন্দুরি','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',200,'','',6,true,true),
  ('chicken-reshmi-kebab','grill','Chicken Reshmi Kebab','চিকেন রেশমি কাবাব','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',200,'','',7,true,true),
  ('chicken-hariyali-kebab','grill','Chicken Hariyali Kebab','চিকেন হারিয়ালি কাবাব','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',200,'','',8,true,true),
  ('chicken-afghani-kebab','grill','Chicken Afghani Kebab','চিকেন আফগান কাবাব','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',200,'','',9,true,true),
  ('chicken-grill-half','grill','Chicken Grill (Half)','চিকেন গ্রিল (হাফ)','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',NULL,'','',10,true,true),
  ('chicken-grill-full','grill','Chicken Grill (Full)','চিকেন গ্রিল (ফুল)','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',NULL,'','',11,true,true),
  ('charcoal-grill-half','grill','Charcoal Grill (Half)','চারকোল গ্রিল (হাফ)','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',NULL,'','',12,true,true),
  ('charcoal-grill-full','grill','Charcoal Grill (Full)','চারকোল গ্রিল (ফুল)','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',NULL,'','',13,true,true),
  ('chicken-naga-boti-chap','chap','Chicken Naga Boti Chap','চিকেন নাগা বটি চাপ','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',220,'','',14,true,true),
  ('beef-chap','beef','Beef Chap','বিফ চাপ','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',230,'','',15,true,true),
  ('beef-boti-kebab','beef','Beef Boti Kebab','বিফ বটি কাবাব','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',230,'','',16,true,true),
  ('beef-afghani-kebab','beef','Beef Afghani Kebab','বিফ আফগান কাবাব','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',300,'','',17,true,true),
  ('beef-kala-bhuna','beef','Beef Kala Bhuna','বিফ কালা ভুনা','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',300,'','',18,true,true),
  ('beef-nehari','beef','Beef Nehari','বিফ নেহারি','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',350,'','',19,true,true),
  ('fried-rice','rice','Fried Rice','ফ্রাইড রাইস','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',120,'','',20,true,true),
  ('duck-bhuna','special','Duck Bhuna','হাঁস ভুনা','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',300,'','',21,true,true),
  ('naan','naan','Plain Naan','প্লেন নান','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',40,'','',22,true,true),
  ('butter-naan','naan','Butter Naan','বাটার নান','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',50,'','',23,true,true),
  ('butter-garlic-naan','naan','Butter Garlic Naan','বাটার গার্লিক নান','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',60,'','',24,true,true),
  ('chilli-butter-garlic-naan','naan','Chilli Butter Garlic Naan','চিলি বাটার গার্লিক নান','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',70,'','',25,true,true),
  ('special-naan','naan','Special Naan','স্পেশাল নান','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',150,'','',26,true,true),
  ('biscuit-naan','naan','Biscuit Naan','বিস্কুট নান','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',180,'','',27,true,true),
  ('roti','naan','Roti','রুটি','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',20,'','',28,true,true),
  ('raita-salad','salad','Raita Salad','রায়তা সালাদ','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',20,'','',29,true,true),
  ('mixed-salad','salad','Mixed Salad','মিক্সড সালাদ','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',100,'','',30,true,true),
  ('fresh-fruit-drink-small','drinks','Fresh Fruit Drink (small)','ফ্রেশ ফ্রুট ড্রিংক (ছোট)','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',NULL,'','',31,true,true),
  ('fresh-fruit-drink-large','drinks','Fresh Fruit Drink (large)','ফ্রেশ ফ্রুট ড্রিংক (বড়)','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',NULL,'','',32,true,true),
  ('strawberry-lassi','drinks','Strawberry Lassi','স্ট্রবেরি লাচ্ছি','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',140,'','',33,true,true),
  ('salt-lassi','drinks','Salt Lassi','সল্ট লাচ্ছি','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',140,'','',34,true,true),
  ('sweet-lassi','drinks','Sweet Lassi','মিষ্টি লাচ্ছি','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',140,'','',35,true,true),
  ('special-coffee','drinks','Special Coffee','স্পেশাল কফি','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',180,'','',36,true,true),
  ('lemon-water','drinks','Lemon Water','লেবু পানি','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',110,'','',37,true,true),
  ('soft-drinks-mrp','drinks','Soft Drinks (MRP)','সফট ড্রিংকস (এমআরপি)','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',NULL,'','',38,true,true),
  ('mineral-water-mrp','drinks','Mineral Water (MRP)','মিনারেল ওয়াটার (এমআরপি)','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',NULL,'','',39,true,true),
  ('oreo-shake','shakes','Oreo Shake','ওরিও শেক','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',200,'','',40,true,true),
  ('chocolate-milk-shake','shakes','Chocolate Milk Shake','চকলেট মিল্ক শেক','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',NULL,'','',41,true,true),
  ('espresso','coffee','Espresso','এসপ্রেসো','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',150,'','',42,true,true),
  ('double-espresso','coffee','Double Espresso','ডাবল এসপ্রেসো','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',220,'','',43,true,true),
  ('americano','coffee','Americano','আমেরিকানো','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',160,'','',44,true,true),
  ('cappuccino','coffee','Cappuccino','ক্যাপুচিনো','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',180,'','',45,true,true),
  ('caf-latte','coffee','Café Latte','ক্যাফে লাতে','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',200,'','',46,true,true),
  ('flat-white','coffee','Flat White','ফ্ল্যাট হোয়াইট','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',220,'','',47,true,true),
  ('mocha','coffee','Mocha','মোকা','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',260,'','',48,true,true),
  ('caramel-latte','coffee','Caramel Latte','ক্যারামেল লাতে','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',260,'','',49,true,true),
  ('vanilla-latte','coffee','Vanilla Latte','ভ্যানিলা লাতে','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',260,'','',50,true,true),
  ('iced-americano','coffee','Iced Americano','আইসড আমেরিকানো','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',180,'','',51,true,true),
  ('iced-latte','coffee','Iced Latte','আইসড লাতে','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',220,'','',52,true,true),
  ('iced-caramel-latte','coffee','Iced Caramel Latte','আইসড ক্যারামেল লাতে','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',260,'','',53,true,true),
  ('iced-mocha','coffee','Iced Mocha','আইসড মোকা','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',280,'','',54,true,true),
  ('cold-coffee-classic','coffee','Cold Coffee Classic','কোল্ড কফি ক্ল্যাসিক','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',220,'','',55,true,true),
  ('cold-coffee-with-ice-cream','coffee','Cold Coffee with Ice Cream','আইসক্রিমসহ কোল্ড কফি','From Chap Khana’s photographed menu. Confirm current price and availability before ordering.','চাপ খানার মেনুর ছবি থেকে নেওয়া। অর্ডারের আগে বর্তমান দাম ও প্রাপ্যতা নিশ্চিত করুন।',300,'','',56,true,true),
  ('basmati-kacchi','rice','Basmati Kacchi','বাসমতি কাচ্চি','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',250,'','Confirm branch',57,false,false),
  ('beef-tehari','rice','Beef Tehari','বিফ তেহারি','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',180,'','Confirm branch',58,false,false),
  ('beef-achari-khichuri','rice','Beef Achari Khichuri','বিফ আচারী খিচুড়ি','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',180,'','Confirm branch',59,false,false),
  ('koyel-roast-and-polao','rice','Koyel Roast and Polao','কোয়েল রোস্ট ও পোলাও','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',240,'','Confirm branch',60,false,false),
  ('chicken-biryani','rice','Chicken Biryani','চিকেন বিরিয়ানি','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',150,'','Confirm branch',61,false,false),
  ('basmati-rice-deshi','rice','Basmati Rice (Deshi)','বাসমতি ভাত (দেশি)','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',40,'','Confirm branch',62,false,false),
  ('beef-tikka','special','Beef Tikka','বিফ টিক্কা','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',70,'','Confirm branch',63,false,false),
  ('chicken-tikka','special','Chicken Tikka','চিকেন টিক্কা','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',70,'','Confirm branch',64,false,false),
  ('chicken-jhal-fry','special','Chicken Jhal Fry','চিকেন ঝাল ফ্রাই','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',150,'','Confirm branch',65,false,false),
  ('shorisha-ilish','special','Shorisha Ilish','সরিষা ইলিশ','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',200,'','Confirm branch',66,false,false),
  ('rui-fish','special','Rui Fish','রুই মাছ','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',150,'','Confirm branch',67,false,false),
  ('coral-fish','special','Coral Fish','কোরাল মাছ','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',150,'','Confirm branch',68,false,false),
  ('shrimp-malai-curry','special','Shrimp Malai Curry','চিংড়ি মালাইকারি','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',180,'','Confirm branch',69,false,false),
  ('baila-fish','special','Baila Fish','বাইলা মাছ','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',140,'','Confirm branch',70,false,false),
  ('dry-fish-bhorta','special','Dry Fish Bhorta','শুঁটকি ভর্তা','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',20,'','Confirm branch',71,false,false),
  ('begun-bhorta','special','Begun Bhorta','বেগুন ভর্তা','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',20,'','Confirm branch',72,false,false),
  ('kola-bhorta','special','Kola Bhorta','কলা ভর্তা','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',20,'','Confirm branch',73,false,false),
  ('tomato-chutney','special','Tomato Chutney','টমেটো চাটনি','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',20,'','Confirm branch',74,false,false),
  ('dal','special','Dal','ডাল','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',20,'','Confirm branch',75,false,false),
  ('vegetables','special','Vegetables','সবজি','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',30,'','Confirm branch',76,false,false),
  ('lebupani','juice','Lebupani','লেবু পানি (পুরোনো মেনু)','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',40,'','Confirm branch',77,false,false),
  ('apple-juice','juice','Apple Juice','আপেল জুস','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',120,'','Confirm branch',78,false,false),
  ('orange-juice','juice','Orange Juice','কমলা জুস','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',120,'','Confirm branch',79,false,false),
  ('pineapple-juice','juice','Pineapple Juice','আনারস জুস','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',120,'','Confirm branch',80,false,false),
  ('mango-juice','juice','Mango Juice','আম জুস','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',120,'','Confirm branch',81,false,false),
  ('green-mango-juice','juice','Green Mango Juice','কাঁচা আমের জুস','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',110,'','Confirm branch',82,false,false),
  ('watermelon-juice','juice','Watermelon Juice','তরমুজের জুস','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',100,'','Confirm branch',83,false,false),
  ('papaya-juice','juice','Papaya Juice','পেঁপের জুস','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',140,'','Confirm branch',84,false,false),
  ('lassi-regular','juice','Lassi Regular','লাচ্ছি রেগুলার','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',100,'','Confirm branch',85,false,false),
  ('mint-lassi','juice','Mint Lassi','মিন্ট লাচ্ছি','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',120,'','Confirm branch',86,false,false),
  ('borhani-250ml','drinks','Borhani (250ml)','বোরহানি (২৫০ মি.লি.)','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',40,'','Confirm branch',87,false,false),
  ('borhani-500ml','drinks','Borhani (500ml)','বোরহানি (৫০০ মি.লি.)','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',80,'','Confirm branch',88,false,false),
  ('borhani-1-litre','drinks','Borhani (1 litre)','বোরহানি (১ লিটার)','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',150,'','Confirm branch',89,false,false),
  ('faluda-regular','dessert','Faluda Regular','ফালুদা রেগুলার','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',160,'','Confirm branch',90,false,false),
  ('faluda-special','dessert','Faluda Special','ফালুদা স্পেশাল','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',200,'','Confirm branch',91,false,false),
  ('firni','dessert','Firni','ফিরনি','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',50,'','Confirm branch',92,false,false),
  ('pudding','dessert','Pudding','পুডিং','From an older or branch-specific printed menu; confirm this item and price with the Khilkhet owner before publishing.','পুরোনো/অন্য শাখার মেনু থেকে নেওয়া। প্রকাশের আগে শাখা, আইটেম ও দাম নিশ্চিত করুন।',60,'','Confirm branch',93,false,false)
on conflict (id) do update set
  category = excluded.category,
  name = excluded.name,
  name_bn = excluded.name_bn,
  description = excluded.description,
  description_bn = excluded.description_bn,
  price = excluded.price,
  image_url = excluded.image_url,
  badge = excluded.badge,
  sort_order = excluded.sort_order
where public.menu_items.price is null;

-- Deactivate the earlier unpriced placeholder; do not remove any paid/owner-edited item.
update public.menu_items set active=false
where id='grilled-chicken' and price is null;

-- DO NOT turn online ordering on automatically. Admin must confirm prices,
-- available items, branch, delivery coverage, and current hours.
commit;
